/**
 * In-memory store shared by all gateways in the simulator (issue #55).
 *
 * Single responsibility: save created transactions indexed by their native
 * identifier and retrieve them by that same identifier.
 *
 * Implemented with a Node.js Map because the simulator is a testing tool,
 * not a production system. Do NOT add persistence (database, file, Redis)
 * to this class: ephemeral state is intentional and desirable; restarting
 * the simulator clears the store, which is the correct behavior in a
 * testing environment.
 *
 * The module exports a single instance (`transactionStore`). Node.js caches
 * ES modules, so any file that imports `transactionStore` will get the same
 * instance without needing an explicit Singleton pattern. This guarantees
 * that all gateways (Wompi, Rapyd, Mercado Pago, Kushki) share the same
 * store when implemented in later iterations.
 */
export class TransactionStore {
  private readonly store = new Map<string, unknown>();

  /**
   * Saves a transaction in the store indexed by its native identifier.
   * If a transaction with that id already existed, it is overwritten.
   *
   * @param id           Native gateway identifier (e.g. the UUID generated by Wompi).
   * @param transaction  Transaction object in its native gateway form.
   */
  save(id: string, transaction: unknown): void {
    this.store.set(id, transaction);
  }

  /**
   * Retrieves a transaction by its native identifier.
   *
   * @param id  Native gateway identifier.
   * @returns   The saved transaction object, or `undefined` if it does not exist.
   */
  findById(id: string): unknown {
    return this.store.get(id);
  }

  /**
   * Removes all transactions from the store.
   * Useful in `afterEach` / `beforeEach` test hooks to guarantee isolation.
   */
  clear(): void {
    this.store.clear();
  }

  /**
   * Returns the number of transactions currently saved.
   * Useful for assertions in tests.
   */
  size(): number {
    return this.store.size;
  }
}

/** Shared instance used by all gateways in the simulator. */
export const transactionStore = new TransactionStore();